"""fix add review

Revision ID: 6481e6dcb1da
Revises: 66641c75a645
Create Date: 2024-03-15 15:07:23.246710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6481e6dcb1da'
down_revision = '66641c75a645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_reviews_item_is_items', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_reviews_item_id_items'), 'items', ['item_id'], ['id'])
        batch_op.drop_column('item_is')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_is', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_reviews_item_id_items'), type_='foreignkey')
        batch_op.create_foreign_key('fk_reviews_item_is_items', 'items', ['item_is'], ['id'])
        batch_op.drop_column('item_id')

    # ### end Alembic commands ###
